# Generated by Django 4.0.5 on 2022-06-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('realname', models.CharField(max_length=50, verbose_name='이름')),
                ('birthday', models.DateField(verbose_name='생일')),
                ('age', models.IntegerField(default=0, verbose_name='나이')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='취미')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('introduction', models.TextField(null=True, verbose_name='자기소개')),
                ('profile_image', models.ImageField(null=True, upload_to='', verbose_name='프로필 사진')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.hobby')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(through='userapp.UserProfileHobby', to='userapp.hobby', verbose_name='취미'),
        ),
    ]
