# Generated by Django 4.0.5 on 2022-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('start_at', models.DateField(verbose_name='노출 시작일')),
                ('end_at', models.DateField(verbose_name='노출 종료일')),
                ('is_active', models.BooleanField(verbose_name='활성화 여부')),
            ],
        ),
    ]
